### PR TITLE
manifests: update

### PR DESCRIPTION
**Pull request by JoshuaBatty**

### CODE REVIEW

**Comment by kayagokalp** [comment]
Nice! Thanks for handling this, we just need [0.42.0](https://github.com/FuelLabs/sway/pull/4755) to be released and re-run the script so that it creates the latest again. Which should hopefully, fix our macos latest problems.

**Comment by JoshuaBatty** [comment]
Cool, i'll re-run the script once that PR lands and see if it fixes the problem.

**Comment by kayagokalp** [comment]
🎉 looks like macos-latest fuel is succeeded, looks promising!

**Comment by kayagokalp** [comment]
Renamed the PR to match other manifest refresh commits.

**Review by kayagokalp — APPROVED** [review]

**Pull request merged**
